### DISCUSSION TITLE
TLS 1.2 and 1.3 support?

### DISCUSSION THREAD

**Discussion by iliepandia** [Hyperfoil/Hyperfoil#554] [Q&A] [answered]
Hello, 

Trying to setup a basic load test, and the connections all get stuck at TLS + HTTP 1.x phase. 

The server I am trying to connect to only allows for TLS 1.2 and 1.3 but not 1.1 

I am trying to determine what is the problem, and I wanted to check for TLS support.

**Comment by lampajr** [comment]
Hello @iliepandia, first of all thanks for using Hyperfoil!

I just did a simple check on my side and it looks working using Http2 + TLS1.3 and also Http1.1 + TLS1.3 (I tried by setting up a simple server). So it shouldn't be a problem if the server under test only allows TLS 1.2 and 1.3.

Can you please provide some more details on your issue? like your Hyperfoil setup (standalone or clustered) and what kind of errors you see from the logs (especially on the controller/agent side)? Feel free to remove any kind of sensitive data.

**Comment by iliepandia** [comment]
Sure, here is the configuration file. I cannot post the site link, since that is private, but I can tell you that is an AWS EC2 instance behind the AWS LoadBalancer. I see a graph in the load balancer showing Client TLS Negotiation errors. Postman and cURL connect no problem.

I just tried with the example.com domain and I have the same problem. So there is something happening on my local host. 

```yaml
name: single-endpoint
http:
  - host: https://example.com
    sharedConnections: 1500
    allowHttp1x: false
    allowHttp2: true
phases:
  - offerIndexRampUp:
      increasingRate:
        duration: 5s
        maxIterations: 10
        maxSessions: 550
        initialUsersPerSec:
          base: 0
          increment: 5
        targetUsersPerSec:
          base: 5
          increment: 5
        scenario:
          - browse:
            - httpRequest:
                POST: /test-page
            - thinkTime:
                duration: 200ms
```


This is what I see for connections

```
 NAME  STATUS  STARTED  REMAINING  COMPLETED  TOTAL DURATION  DESCRIPTION

———————————————————————————————————————————————————————————————————————————————————————————————
TARGET                                    TYPE                MIN   MAX
example.com:443                           TLS + HTTP 2        1251  1251
                                          blocked sessions       0     0
                                          in-flight requests     0     0
                                          used connections       0     0
Press [s] for status, [t] for stats, [e] for sessions, [c] for connections or Ctrl+C to stop watching...
```
