### ISSUE TITLE
hyperfoil_setup ignores hyperfoil_version var to get specific version.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Hyperfoil#106]
Hi,
 I found the downloaded version of hyperfoil for the 7.x release will get 0.7.1 instead of 0.7.0.

Here is a reproducer, hosts file and playbook
hosts

```
[hyperfoil_controller]
localhost ansible_hostname=localhost ansible_host=localhost ansible_user=root
```

hf.yml

```
- hosts: localhost
  tasks:
  - include_role:
      name: hyperfoil.hyperfoil_setup
    vars:
      hyperfoil_version: "0.7"
```

after running the playbook I am seeing this

```
$ ls /tmp/hyperfoil/hyperfoil-0.7.*/lib/hyperfoil-*
/tmp/hyperfoil/hyperfoil-0.7.1/lib/hyperfoil-api-0.7.1.jar
/tmp/hyperfoil/hyperfoil-0.7.1/lib/hyperfoil-cli-0.7.1.jar
/tmp/hyperfoil/hyperfoil-0.7.1/lib/hyperfoil-clustering-0.7.1.jar
/tmp/hyperfoil/hyperfoil-0.7.1/lib/hyperfoil-controller-api-0.7.1.jar
/tmp/hyperfoil/hyperfoil-0.7.1/lib/hyperfoil-core-0.7.1.jar
/tmp/hyperfoil/hyperfoil-0.7.1/lib/hyperfoil-k8s-deployer-0.7.1.jar
$ ls -l /tmp/hyperfoil/hyperfoil-0.7.*/lib/hyperfoil-api-*
-rw-rw-r--. 1 root root 162678 Feb 26 08:19 /tmp/hyperfoil/hyperfoil-0.7.1/lib/hyperfoil-api-0.7.1.jar
$
```
 The library has a timestamp after the 0.7 release date of 12th Feb 2020.
