### ISSUE TITLE
Option to automatically send CORS requests

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Hyperfoil#143]
All modern requests issue the OPTIONS requests for checking CORS; Hyperfoil should offer a switch to do the same.

**Comment by rvansa** [comment]
I guess this won't be fully automatic because CORS are issued for a request invoked from a script; however we can have something like

```yaml
- httpRequest:
    POST: /foo
    corsFrom: http://example.com
```
That would prepend another `httpRequest` before this one, sending the OPTIONS with proper headers and if this returns a non-2xx status it would invoke a copy of original request handlers with 403 response.
