### ISSUE TITLE
Can not define randomItem: file: in initialSequence in an aliased scenario 

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Hyperfoil#17]
If you define a randomItem step loading from a file in an intialSequence defined in an aliased scenario, when that alised scenario is referenced in another phase, the file is reloaded, but data already exists in String[] list.

the following exception is thrown:
BenchmarkDefinitionException("randomItem cannot combine `list` and `file`");

**Comment by johnaohara** [comment]
e.g. 

```
name: benchmark
http:
  baseUrl: http://localhost:8080
  sharedConnections: 50
phases:
- rampUp:
    rampPerSec:
      initialUsersPerSec: 1
      targetUsersPerSec: 1000
      duration: 10s
      maxSessionsEstimate: 50
      scenario: &scenario
        initialSequences:
        - load_fruits:
          - randomItem:
              file: /home/user/Work/projects/protean/rest-http-crud/hyperfoil-runner/src/test/resources/fruits.txt
              var: fruits
        sequences:
        - get_random-fruit:
          - randomItem:
              fromVar: fruits
              var: selectedFruit
        - get_index:
          - httpRequest:
              GET: /
              sync: true
              handler:
                status:
                  range: 200
        - get_fruits:
          - httpRequest:
              GET: /fruits
              sync: true
              handler:
                status:
                  range: 200

 - steadyState:
     constantPerSec:
       usersPerSec: 1000
       duration: 60s
       scenario: *scenario
```
