### ISSUE TITLE
Reduce nesting of scenario

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Hyperfoil#181]
We could remove one level of indentation for the scenario and other common properties by writing phases like this:
```yaml
phases:
  myPhase:
    duration: ...
    constantRate:
      userPerSec: ...
    scenario: ...
```
In code that would probably mean delegating the phase-type-specific part into other class (we cannot instantiate the phase before we know the type while reading the benchmark - that's the reason why currently we use the nesting).

Also we should support (and prefer!) defining phases as mapping rather than in a list. Were it a list we could get down one more level by setting the name as a property:

```yaml
phases:
- name: myPhase
  duration: ...
  constantRate:
    userPerSec: ...
  scenario: ...
```

Is it worth it? Opinions @johnaohara @whitingjr ?
