### ISSUE TITLE
Scenario with single named endpoint does not parse correctly

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Hyperfoil#230]
```
name: send-to-cloud
http:
- host: http://192.168.0.1/
  name: my-perf-bridge
  sharedConnections: 5
  connectionStrategy: ALWAYS_NEW
phases:
- send-cloud-events:
    always:
      duration: 5m
      maxDuration: 6m
      users: 1
      scenario:
      - send:
        - httpRequest:
            POST: ...
            body: ...
            headers:
              content-type: application/json
              authorization: Bearer XYZ
```

Hyperfoil complains with:

```
Duplicate key my-perf-bridge (attempted merging values io.hyperfoil.http.connection.ConnectionAllocator@24015b22 and io.hyperfoil.http.connection.ConnectionAllocator@24015b22)
```
