### ISSUE TITLE
BenchmarkDefinitionException - Duplicate HTTP endpoint for authority

### ISSUE THREAD

**Issue by afalhambra** [Hyperfoil/Hyperfoil#242]
*Duplicate HTTP endpoint for authority*

In a project of ours, we're trying to create a scenario in Hyperfoil where we need to have 2 different endpoints. Problem is that these endpoints may be having the same host and port in some environments, and completely different in others. So in those scenarios where the hostname and port are the same, Hyperfoil throws an exception saying `Duplicate HTTP endpoint for authority...` - [see](https://github.com/Hyperfoil/Hyperfoil/blob/master/http/src/main/java/io/hyperfoil/http/config/HttpPluginBuilder.java#L96).

For instance:

```
http:
- host: http://192.168.49.2
  name: bridge-1
  sharedConnections: 10
  connectionStrategy: ALWAYS_NEW
- host: http://192.168.49.2
  name: bridge-2
  sharedConnections: 10
  connectionStrategy: ALWAYS_NEW
```

IMO, correct behaviour should be that when two or more hosts share the same base domain and port but are defined with different names, then they should be considered different, so no exception should be thrown, otherwise, it should be fine to throw such exception when sharing base domain and port but:
- no name is defined
- they share same name
