### ISSUE TITLE
orderedSequences missing a step before preparing request with variables.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Hyperfoil#311]
Using this benchmark configuration the benchmark is cancelled due to a missing `villian` variable.

```Errors:
in-vm: Variable villain is not set!
```

There are 3 requests configured in an ordered sequence. In reality only two executed and `getRandomVillainFighter` get's completely ignored. Discovered using Wireshark.

```name: fight
http:
- host: localhost
  port: 8082
  sharedConnections: !param SHARED_CONNECTIONS 800

#  Disable stopping the scenario on 4xx or 5xx response
ergonomics:
  autoRangeCheck: false
  stopOnInvalid: false

phases:
  - performFight:
      constantRate:
        usersPerSec: !param USERS_PER_SEC 5
        maxSessions: !param MAX_SESSIONS 1600
        duration: !param DURATION 1m
        scenario:
          orderedSequences:
          - getRandomHeroFighter:
              - httpRequest:
                  GET: /api/fights/randomfighters
                  handler:
                    body:
                    - json:
                        query: .hero
                        format: BYTES
                        toVar: hero
          - getRandomVillainFighter:
              - httpRequest:
                  GET: /api/fights/randomfighters
                  handler:
                    body:
                      - json:
                          query: .villain
                          format: BYTES
                          toVar: villain
          - doFight:
              - httpRequest:
                  POST: /api/fights
                  headers:
                    content-type: application/json
                  body:
                    pattern: >-
                      { "hero": "${hero}" , "villain": "${villain}" }
```

![orderedSequences-missing-getRandomVillainFighter-request](https://github.com/Hyperfoil/Hyperfoil/assets/708428/e27122c5-3ad1-433a-99a6-1a6996dc2cb6)

It seems the `doFight` request is being prepared too early.

**Comment by whitingjr** [comment]
Despite explicitly defining the http request execution order the `orderedSequences` is not working as documented.
 A workaround is instead to define `initialSequences` followed by `sequences`. This will achieve the desired effect.

**Comment by whitingjr** [comment]
reproducer is to start services in this [repo](https://github.com/quarkusio/quarkus-super-heroes)  using this command
```$ podman-compose -f deploy/docker-compose/java17.yml up```
then execute benchmark run using 
```name: perform-fight
http:
- host: localhost
  port: 8082
  sharedConnections: !param SHARED_CONNECTIONS 30

phases:
  - performFight:
      constantRate:
        usersPerSec: !param USERS_PER_SEC 20
        maxSessions: !param MAX_SESSIONS 100
        duration: !param DURATION 30
        scenario:
          orderedSequences:
          - getRandomFighters:
              - httpRequest:
                  GET: /api/fights/randomfighters
                  handler:
                    body:
                    - json:
                        query: .
                        format: BYTES
                        toVar: randomFighters
          - doFight:
              - httpRequest:
                  POST: /api/fights
                  headers:
                    content-type: application/json
                  body:
                    fromVar: randomFighters
```

**Comment by franz1981** [comment]
I'm banging my head how to reproduce it with simple actions, but failing

```yaml
name: ordered-sequence
phases:
- single:
    always:
      users: 1
      duration: 2
      scenario:
        orderedSequences:
          - first:
            - addToInt:
                var: counter
                value: 1
                orElseSetTo: 43
            - log: counter@first = ${counter}
          - second:
            - addToInt: counter--
            - log: counter@second = ${counter}
          - third:
            - fail:
                intCondition: counter != 42
```
is working as expected for me
