### ISSUE TITLE
httpRequest parsing fails without error for multi-host without authority

### ISSUE THREAD

**Issue by johnaohara** [Hyperfoil/Hyperfoil#315]
With a benchmark definition with more than one host, if the `authority` property is not defined for a `httpRequest`, uploading the benchmark definition fails without any meaningful error;

```
[hyperfoil@in-vm]$ upload /benchmarks/horreum-tfb.hf.yaml
ERROR: null
Use --print-stack-trace to display the whole stack trace of this error.
Unknown error.

```

e.g.

```
name: horreum-tfb
http:
-  host: http://localhost:8080 
   sharedConnections: 10 
-  host: http://localhost:9080
   sharedConnections: 1
phases:
- configure:
    atOnce:
      users: 1
      scenario:
        initialSequences:
        - uploadDefs:
          - httpRequest:
              authority: localhost:9080
              POST: /realms/horreum/protocol/openid-connect/token?username=user&password=secret&grant_type=password&client_id=horreum-ui
              handler:
                body:
                  json:
                    query: .access_token
                    toVar: access_token
          - httpRequest:
              # authority: localhost:8080
              POST: /api/schema
              headers:
                authorization: Bearer ${access_token}
              body:
                fromFile: config/techempower-runtime.schema.json
```
