### ISSUE TITLE
newSequence not working 

### ISSUE THREAD

**Issue by thiagohora** [Hyperfoil/Hyperfoil#441]
**Describe the bug**
I'm trying to create a nested look using `newSequence` as in my scenario, I need to create one resource and, for each of those resources, make 10 of the other ones.

**To Reproduce**
upload test.yml

```
scenario:
  - normalUsage:
      - loop:
          counterVar: myCounter
          repeats: 100
          steps:
            - randomCsvRow:
                file: generated_data.csv
                columns:
                    0: id
                    1: project_name
                    2: name
            - set:
                var: traceId
                value: ${id}  
            - httpRequest:
                POST: "/v1/private/traces"
                headers:
                  Content-Type: application/json
                  Accept: application/json
                body: |
                  {
                      "id": "${id}",
                      "project_name": "${project_name}",
                      "name": "${name}"
                  }
            - newSequence:
                name: "spanSequence"
                steps:
                  - loop:
                      counterVar: myCounter2
                      repeats: 10  # Create 10 spans for each trace
                      steps:
                        - randomCsvRow:
                            file: generated_spans.csv
                            columns:
                                0: span_id
                                1: span_name
                        - httpRequest:
                            POST: "/v1/private/spans"
                            headers:
                              Content-Type: application/json
                              Accept: application/json
                            body: |
                              {
                                  "traceId": "${traceId}",
                                  "id": "${span_id}",
                                  "name": "${span_name} ${counter}"
                              }

```

**Expected behavior**
be able to perform a loop inside another loop using the new sequence

**Additional context**
quay.io/hyperfoil/hyperfoil:latest

**Comment by lampajr** [comment]
Hi @thiagohora, first of all thanks a lot for using Hyperfoil :pray: 

Coming back to the issue, what is the error you're getting? Is it a benchmark validation failure? Do you mind sharing the stacktrace or error you are getting from the logs or cli?

Giving a quick look at you benchmark I think the issue might be in how you defined the `newSequence`. In according to the documentation [1] the `newSwquence` should only accept a `name` which is the name of the sequence to use (a sequence that you must define in the `sequences`).

You can check a more complex scenario here https://hyperfoil.io/docs/getting-started/quickstart3/ which seems pretty close to your use case.

[1] https://hyperfoil.io/docs/reference/actions/action_newsequence/

**Comment by lampajr** [comment]
Something like this might work for your use case:

```yaml
scenario:
  initialSequences:
  - normalUsage:
      - loop:
          counterVar: myCounter
          repeats: 100
          steps:
            - randomCsvRow:
                file: generated_data.csv
                columns:
                    0: id
                    1: project_name
                    2: name
            - set:
                var: traceId
                value: ${id}  
            - httpRequest:
                POST: "/v1/private/traces"
                headers:
                  Content-Type: application/json
                  Accept: application/json
                body: |
                  {
                      "id": "${id}",
                      "project_name": "${project_name}",
                      "name": "${name}"
                  }
            - newSequence: spanSequence
  sequences:
    # [N] represents the maximum concurrency level which strictly depends on your rate and expectation
    - spanSequence[100]:
      - loop:
          # [.] is required as the counter must be sequence scoped
          counterVar: myCounter2[.]
          repeats: 10  # Create 10 spans for each trace
          steps:
            - randomCsvRow:
                file: generated_spans.csv
                columns:
                    0: span_id
                    1: span_name
            - httpRequest:
                POST: "/v1/private/spans"
                headers:
                  Content-Type: application/json
                  Accept: application/json
                body: |
                  {
                      "traceId": "${traceId}",
                      "id": "${span_id}",
                      "name": "${span_name} ${counter}"
                  }

```
