### ISSUE TITLE
ThinkTime seems to cause Hyperfoil to hang indefinetly.

### ISSUE THREAD

**Issue by iliepandia** [Hyperfoil/Hyperfoil#522]
**Describe the bug**

A load works fine until I add `thinkTime` to it. When I add thinkTime to simulate the user looking at the response, the phase will finish, but will never terminate, so I wait indefinitely for it. I can define a maxDuraiton and that will force terminate the phase, but that is not what I want. Also the sessions and connections drop to 0, so I don't understand what is Hyperfoil waiting for.

**To Reproduce**

```
name: micro-load1
http:
  host: http://localhost:8181
  sharedConnections: 1500
phases:
  # Just hit the front end with requests for a simple page
  - userIndexRampUp:
      increasingRate:
        duration: 5s
        maxIterations: 10
        maxSessions: 550
        initialUsersPerSec:
          base: 0
          increment: 5
        targetUsersPerSec:
          base: 5
          increment: 5
        scenario:
          - browse:
              - httpRequest:
                  GET: /payments/
                  sla:
                    - meanResponseTime: 2s
  # Do a buying session ramp up
  # - User logs in
  # - loads the product list
  # - opens a product
  # - places an order for a couple of products
  # - executes a payment
  - userBuyingRampUp:
      increasingRate:
        duration: 6
#        maxDuration: 20 #this was needed because some users hang for some reason!!!
        maxIterations: 10
        maxSessions: 120
        initialUsersPerSec:
          base: 0
          increment: 3
        targetUsersPerSec:
          base: 3
          increment: 3
        scenario:
          - login:
              # load a valid email from a file
              - randomCsvRow:
                  file: emails.txt
                  columns:
                    0: email
              - httpRequest:
                  headers:
                    accept: application/json
                  POST: /users/api/login
                  body:
                    form:
                      - name: email
                        fromVar: email
                      - name: password
                        value: "password"
                  handler:
                    body:
                      # extract the token
                      json:
                        query: ".access_token"
                        toVar: token
                  sla:
                    - meanResponseTime: 2s
          - get-product-list:
              - httpRequest:
                  GET: /products/api/list
                  headers:
                    accept: application/json
                    authorization: Bearer ${token}
                  sla:
                    - meanResponseTime: 2s
              - thinkTime:
                  duration: 1s #user looks at the product for a bit
          - look-at-a-product:
              - httpRequest:
                  GET: /products/api/1
                  headers:
                    accept: application/json
                    authorization: Bearer ${token}
                  sla:
                    - meanResponseTime: 2s
              - thinkTime:
                  duration: 500ms #user looks at the product for a bit
          - place-an-order:
              - httpRequest:
                  POST: /orders/api/create
                  body:
                    form:
                      - name: "order_lines[0][product_id]"
                        value: "1"
                      - name: "order_lines[0][quantity]"
                        value: "100"
                      - name: "order_lines[1][product_id]"
                        value: "2"
                      - name: "order_lines[1][quantity]"
                        value: "100"
                      - name: "order_lines[2][product_id]"
                        value: "3"
                      - name: "order_lines[2][quantity]"
                        value: "10"
                  sla:
                    - meanResponseTime: 2s
                  headers:
                    accept: application/json
                    authorization: Bearer ${token}
                  handler:
                    body:
                      # extract the order number
                      json:
                        query: ".id"
                        toVar: order_id
              - thinkTime:
                  duration: 1s
          - make-a-payment:
              - httpRequest:
                  POST: /payments/api/create
                  body:
                    form:
                      - name: "order_id"
                        fromVar: order_id
                      - name: "transaction_id"
                        value: "12345678901234567890"
                      - name: "notes"
                        value: "stress-test"
                  headers:
                    accept: application/json
                    authorization: Bearer ${token}
                  handler:
                    body:
                      # extract the order number
                      json:
                        query: ".id"
                        toVar: payment_id
                  sla:
                    - meanResponseTime: 2s
              - thinkTime:
                  duration: 1s
```

**Expected behavior**
I would expect this load to eventually finish. But it randomly hangs at interaction 2, 3 or 4 at `userBuyingRampUp` phase.

**Additional context**
none

**Comment by franz1981** [comment]
Hi and thanks for your interest in Hyperfoil

This is likely a different effect of https://github.com/Hyperfoil/hyperfoil.github.io/issues/55 and error logs should report that a specific variable is used without been set.
That applies to each if the http request with some processing in the provided scenario definition; which translate into making expected synchronous sequence executions more explicit (as suggested in the mentioned issue), especially if there are variable which requires to be used later on.

The think time is probably piling up on this, making more likely this problem to happen.
I will check locally what's going on but I suggest to give it a try to explicitly wait for completions, when it makes sense.

**Comment by iliepandia** [comment]
OK, I have added awaitVar: token and that was a huge improvement. 

Most of the runs complete now. But it still hangs. Maybe 2 of 10 times. (Before it was 100% of the time). 

Connections go to zero. 

But sessions stay at 13 (they don't go to zero anymore)

`info`  and `inspect` show a blank screen. 

I looked for the `token` variable in this log file: /tmp/hyperfoil/hyperfoil.local.log - but no results prepping for token. 

Is there another log I should be looking at?

**Comment by iliepandia** [comment]
Ah, there is aslo the `order_id` var I need to wait for... trying with that one as well.

**Comment by iliepandia** [comment]
With this updated code it only hangs once. I restarted hyperfoil and I could not get it to hang anymore:

```yaml
name: micro-load1
http:
  host: http://localhost:8181
  sharedConnections: 1500
phases:
  # Just hit the front end with requests for a simple page
  - userIndexRampUp:
      increasingRate:
        duration: 5s
        maxIterations: 10
        maxSessions: 550
        initialUsersPerSec:
          base: 0
          increment: 5
        targetUsersPerSec:
          base: 5
          increment: 5
        scenario:
          - browse:
              - httpRequest:
                  GET: /payments/
                  sla:
                    - meanResponseTime: 2s
  # Do a buying session ramp up
  # - User logs in
  # - loads the product list
  # - opens a product
  # - places an order for a couple of products
  # - executes a payment
  - userBuyingRampUp:
      increasingRate:
        duration: 6
        maxIterations: 10
        maxSessions: 120
        initialUsersPerSec:
          base: 0
          increment: 3
        targetUsersPerSec:
          base: 3
          increment: 3
        scenario:
          - login:
              # load a valid email from a file
              - randomCsvRow:
                  file: emails.txt
                  columns:
                    0: email
              - httpRequest:
                  headers:
                    accept: application/json
                  POST: /users/api/login
                  body:
                    form:
                      - name: email
                        fromVar: email
                      - name: password
                        value: "password"
                  handler:
                    body:
                      # extract the token
                      json:
                        query: ".access_token"
                        toVar: token
                  sla:
                    - meanResponseTime: 2s
              - awaitVar: token  # we need to wait for this to be set, since the handler is async
          - get-product-list:
              - httpRequest:
                  GET: /products/api/list
                  headers:
                    accept: application/json
                    authorization: Bearer ${token}
                  sla:
                    - meanResponseTime: 2s
              - thinkTime:
                  duration: 1s #user looks at the product for a bit
          - look-at-a-product:
              - httpRequest:
                  GET: /products/api/1
                  headers:
                    accept: application/json
                    authorization: Bearer ${token}
                  sla:
                    - meanResponseTime: 2s
              - thinkTime:
                  duration: 500ms #user looks at the product for a bit
          - place-an-order:
              - httpRequest:
                  POST: /orders/api/create
                  body:
                    form:
                      - name: "order_lines[0][product_id]"
                        value: "1"
                      - name: "order_lines[0][quantity]"
                        value: "100"
                      - name: "order_lines[1][product_id]"
                        value: "2"
                      - name: "order_lines[1][quantity]"
                        value: "100"
                      - name: "order_lines[2][product_id]"
                        value: "3"
                      - name: "order_lines[2][quantity]"
                        value: "10"
                  sla:
                    - meanResponseTime: 2s
                  headers:
                    accept: application/json
                    authorization: Bearer ${token}
                  handler:
                    body:
                      # extract the order number
                      json:
                        query: ".id"
                        toVar: order_id
              - thinkTime:
                  duration: 1s
              - awaitVar: order_id
          - make-a-payment:
              - httpRequest:
                  POST: /payments/api/create
                  body:
                    form:
                      - name: "order_id"
                        fromVar: order_id
                      - name: "transaction_id"
                        value: "12345678901234567890"
                      - name: "notes"
                        value: "stress-test"
                  headers:
                    accept: application/json
                    authorization: Bearer ${token}
                  handler:
                    body:
                      # extract the order number
                      json:
                        query: ".id"
                        toVar: payment_id
                  sla:
                    - meanResponseTime: 2s
              - awaitVar: payment_id
              - thinkTime:
                  duration: 1s

```
