### ISSUE TITLE
Stats report error when they should report redirects 3xx

### ISSUE THREAD

**Issue by iliepandia** [Hyperfoil/Hyperfoil#524]
**Describe the bug**

I have a very basic load, where I test how fast a page redirects to another page

```yaml
name: local-redirect-load
http:
  - host: http://localhost:8083
    sharedConnections: 200
    allowHttp1x: true
    allowHttp2: true
phases:
  # Just hit the index end with requests for a simple page
  - userIndexRampUp:
      increasingRate:
        duration: 5s
        maxIterations: 10
        maxSessions: 300
        initialUsersPerSec:
          base: 1
          increment: 5
        targetUsersPerSec:
          base: 5
          increment: 5
        scenario:
          - browse:
              - httpRequest:
                  GET: /
                  headers:
                    accept: "*/*"
                  handler:
                    autoRangeCheck: false
                    status:
                      range: "3xx"
                  sla:
                    - meanResponseTime: 2s
```

This works fine on local, but when I test it on a real production server I get these strange stats.

The number of **errors** is exactly the number of **redirects**.  And the req/s are zero. 

In the logs I can see this over and over (for the production server). I had to mask the domain and IPs for privacy reasons. 

```
16:52:51,821 INFO  (epollEventLoopGroup-2-1) [i.h.h.s.HttpResponseHandlersImpl] #15 Stopping session due to invalid response (#15, COMPLETING, INVALID) GET masked-domain.com:443/ on connection Http1xConnection{/xxx.xx.xx.x:35156 -> masked-domain.com/x.xx.xxx.xxx:443, status=CLOSED, size=0+0:[]}
```

This is confusing, the 3xx are counted correctly, so then what was the invalid response about?

```text
userIndexRampUp/002  RUNNING  16:52:04.583    1563 ms                             11.00 - 15.00 users per second

————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
Total stats from run 0036
PHASE                METRIC  THROUGHPUT  REQUESTS  MEAN     STD_DEV  MAX      p50      p90      p99      p99.9    p99.99   TIMEOUTS  ERRORS  BLOCKED  2xx
                             3xx         4xx       5xx      CACHE
------------------------------------------------------------------------------------------------------------------------------------------------------------
userIndexRampUp/000  browse  0.00 req/s        15     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns         0      15     0 ns    0
                                     15         0        0        0
------------------------------------------------------------------------------------------------------------------------------------------------------------
userIndexRampUp/001  browse  0.00 req/s        45     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns         0      45     0 ns    0
                                     45         0        0        0
------------------------------------------------------------------------------------------------------------------------------------------------------------
userIndexRampUp/002  browse  0.00 req/s        62     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns         0      62     0 ns    0
                                     62         0        0        0
------------------------------------------------------------------------------------------------------------------------------------------------------------
userIndexRampUp/003  browse  0.00 req/s        95     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns         0      95     0 ns    0
                                     95         0        0        0
------------------------------------------------------------------------------------------------------------------------------------------------------------
userIndexRampUp/004  browse  0.00 req/s       119     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns         0     119     0 ns    0
                                    119         0        0        0
------------------------------------------------------------------------------------------------------------------------------------------------------------
userIndexRampUp/005  browse  0.00 req/s       141     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns         0     141     0 ns    0
                                    141         0        0        0
------------------------------------------------------------------------------------------------------------------------------------------------------------
userIndexRampUp/006  browse  0.00 req/s       161     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns         0     161     0 ns    0
                                    161         0        0        0
------------------------------------------------------------------------------------------------------------------------------------------------------------
userIndexRampUp/007  browse  0.14 req/s       199  1.51 s      0 ns  1.51 s   1.51 s   1.51 s   1.51 s   1.51 s   1.51 s          0     198     0 ns    0
                                    199         0        0        0
------------------------------------------------------------------------------------------------------------------------------------------------------------
userIndexRampUp/008  browse  0.00 req/s       216     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns         0     216     0 ns    0
                                    216         0        0        0
------------------------------------------------------------------------------------------------------------------------------------------------------------
userIndexRampUp/009  browse  0.00 req/s       208     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns     0 ns         0     208     0 ns    0
                                    208         0        0        0
------------------------------------------------------------------------------------------------------------------------------------------------------------
```

At the very end, there are these exceptions

```text
16:52:53,104 WARN  (epollEventLoopGroup-2-1) [i.h.h.c.SharedConnectionPool] Cannot create connection to masked-domain.com:443 (created: 0, failures: 1) java.nio.channels.ClosedChannelException
        at io.netty.channel.epoll.AbstractEpollChannel.doClose(AbstractEpollChannel.java:159)
        at io.netty.channel.epoll.AbstractEpollStreamChannel.doClose(AbstractEpollStreamChannel.java:672)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:754)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:731)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:620)
        at io.netty.channel.epoll.EpollEventLoop.closeAll(EpollEventLoop.java:465)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:430)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**To Reproduce**

Unfortunately I cannot share the production domain, but basically, I am running the above load. Works as you'd expect on local with hunters of redirects per second, but on production, I get those stats.

**Expected behavior**
I would expect to get the 302 reported correctly, no errors , and the number of requests also reported correctly. 

**Additional context**
On local I use HTTP, and on production I use HTTPS. The prod domain is behind Akamai. Redirects are working fine in the browser.
