### ISSUE TITLE
HttpRequest sync is working as expected?

### ISSUE THREAD

**Issue by franz1981** [Hyperfoil/Hyperfoil#527]
While investigating on #522 we have further found different mechanisms to prevent using variable's which are not yet set, due to the asynchronous nature of HttpRequest e.g.
- the `awaitVar` method 
- https://hyperfoil.io/docs/reference/steps/step_awaitallresponses/ : it prevents to make progress since [no in-flight http requests](https://github.com/Hyperfoil/Hyperfoil/blob/master/http/src/main/java/io/hyperfoil/http/steps/AwaitAllResponsesStep.java) are detected, via  which makes it tied to [releasing the http request back to its pool](https://github.com/Hyperfoil/Hyperfoil/blob/965dedefbdd3472a8abdaf93077b00406c0d27f8/http/src/main/java/io/hyperfoil/http/connection/Http1xResponseHandler.java#L545), after [the body handlers are called](https://github.com/Hyperfoil/Hyperfoil/blob/965dedefbdd3472a8abdaf93077b00406c0d27f8/http/src/main/java/io/hyperfoil/http/steps/HttpResponseHandlersImpl.java#L250) while [handling the body parts](https://github.com/Hyperfoil/Hyperfoil/blob/965dedefbdd3472a8abdaf93077b00406c0d27f8/http/src/main/java/io/hyperfoil/http/connection/Http1xResponseHandler.java#L514) e.g. Json body handling with variable settings as in [this unit test](https://github.com/Hyperfoil/Hyperfoil/blob/7df696383ab7778581fd8652cb402a08bdaa0a80/test-suite/src/test/java/io/hyperfoil/test/JsonReplaceTest.java#L38)

The latter method looks more useful when there are many variables set since it would wait till fully completing the request without caring which variable to wait been set.

As usual, the devil is in the details and we noticed that Hyperfoil http requests have already an in-place mechanism which, by default, should make http request been ["synchronous"](https://github.com/Hyperfoil/Hyperfoil/blob/7df696383ab7778581fd8652cb402a08bdaa0a80/http/src/main/java/io/hyperfoil/http/steps/HttpRequestStepBuilder.java#L482) preventing them to complete till their response is fully (received and) processed:
- this is been enforced by placing two steps at https://github.com/Hyperfoil/Hyperfoil/blob/7df696383ab7778581fd8652cb402a08bdaa0a80/http/src/main/java/io/hyperfoil/http/steps/HttpRequestStepBuilder.java#L555-L563
- in addition, on request completion (which includes full response processing) it execute an action to "unblock" the current request at https://github.com/Hyperfoil/Hyperfoil/blob/7df696383ab7778581fd8652cb402a08bdaa0a80/http/src/main/java/io/hyperfoil/http/connection/Http1xResponseHandler.java#L529 and, according to the code which add it to the completion body handlers, it is supposed to be the last one

In short: since `sync` should be true by default, the guard at https://github.com/Hyperfoil/Hyperfoil/blob/7df696383ab7778581fd8652cb402a08bdaa0a80/http/src/main/java/io/hyperfoil/http/steps/AfterSyncRequestStep.java#L17 should prevent already what we suggest users to enforce with additional waiting configurations; it is worth to investigate if the suggestion is not just covering for some bug in the current `sync` implementation.

**Comment by lampajr** [comment]
I tried in a very simple example with one single request and 1 user and it looks working as expected:
```yaml
phases:
  - getTime:
      atOnce:
        users: 1
        scenario:
          - getTime:
              # this takes more than 2s to complete
              - httpRequest:
                  GET: /time
                  headers: 
                    accept: application/json
                  handler:
                    body:
                      - json: .utcTime -> utcTime
              - log: "Current time: ${utcTime}"
```

Adding some debug logs I see:
```bash
afterSyncRequestStep: check - false
afterSyncRequestStep: check - false
onCompletion: releasing request
afterSyncRequestStep: check - true
Current time: 1740584954100
```

This should confirm that the `AfterSyncRequestStep` prevents the sequence to move forward until the handler is executed.

As I said, this is a very simple case where there is just one user performing one single request.. planning to create some more complex scenarios (with higher level of concurrency/parallelism) and see how it behaves.
