### ISSUE TITLE
Generic header to processor adapter

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Hyperfoil#69]
```
headers:
  filter:
    # inline defaults to case-insensitive match, mapping is a StringCondition
    name: Authorization
    # maybe provide toVar OOTB
    processor:
       simple: -> foo
```
