### ISSUE TITLE
Make it possible to edit received JSON

### ISSUE THREAD

**Issue by rvansa** [Hyperfoil/Hyperfoil#73]
```
- httpRequest:
      ...
      handler:
          body:
          - json:
                query: .address.postalCode
                processor:
                   simple:
                      toVar: postalCode
          - simple:
              toVar: response
              format: BYTEBUF
- stringToInt:
     fromVar: postalCode
     toVar: postalCodeInt
- addToInt: postalCodeInt++
- json:
    fromVar: response
    query: .address.postalCode
    replace: "\"${postalCodeInt}\""
    processor:
      simple:
        toVar: response
        format: BYTEBUF
- httpRequest:
      ...
      body:
         fromVar: response
```

**Comment by mossuchida** [comment]
Here is my implementation for defrag fyi
[DefaultHandler.java.zip](https://github.com/Hyperfoil/Hyperfoil/files/4200933/DefaultHandler.java.zip)

**Comment by rvansa** [comment]
Hi  @mossuchida, I've pushed the changes. It's now possilbe to e.g. replace the postal code with a custom string (it's actually a pattern, so you can use `${some.var}`)
```yaml
- httpRequest:
      ...
      handler:
          body:
          - json:
                query: .address.postalCode
                replace: "\"XXXXX\""
                processor:
                   simple:
                      toVar: bodyWithObscuredPostalCode
```

**Comment by rvansa** [comment]
Hmm, looking on the example above, I'll try to streamline the actions the the replace handler...

**Comment by rvansa** [comment]
@mossuchida Please take a look into https://github.com/Hyperfoil/Hyperfoil/blob/master/core/src/test/resources/scenarios/JsonReplaceTest.hf.yaml - I've added a transformer that you could find handy.

**Comment by mossuchida** [comment]
Sorry, it took a while for me to have a look. I am not sure if I can use your implementation for acmeair as it gets whole JSON, then just update one of an element within JSON.
For example, this is original JSON:
```
{
  _id: "uid9985@email.com",
  password: "password",
  status: "GOLD",
  total_miles: NumberLong("0"),
  miles_ytd: NumberLong("0"),
  address: {
    streetAddress1: "123 Main St.",
    streetAddress2: null,
    city: "Anytown",
    stateProvince: "NC",
    country: "USA",
    postalCode: "27617"
  },
  phoneNumber: "919-123-4567",
  phoneNumberType: "BUSINESS"
}
```
Then just change postalCode & street address like this, then POST the updated JSON:
```
{
  _id: "uid9985@email.com",
  password: "password",
  status: "GOLD",
  total_miles: NumberLong("0"),
  miles_ytd: NumberLong("0"),
  address: {
    streetAddress1: "300 Main St.",
    streetAddress2: null,
    city: "Anytown",
    stateProvince: "NC",
    country: "USA",
    postalCode: "30000"
  },
  phoneNumber: "919-123-4567",
  phoneNumberType: "BUSINESS"
}
```

**Comment by rvansa** [comment]
@mossuchida It should be able to do exactly that - you'd store the modified JSON in a var and then load it from the var in the next request `body:`. What is the problem?
Btw what is the `NumberLong("0")`? It does not look like a [valid JSON](https://www.json.org/json-en.html) - I am not 100% sure if HF can parse that.

**Comment by mossuchida** [comment]
Oh, that is from compose. Mongo DB stored Data itself with their syntax. let me fix that.
Current xml that has custom steps will be replaced like this?
```
          - httpRequest:
              headers:
                Authorization:
                  pattern: Bearer ${jwtToken}
              GET:
                pattern: /customer/byid/uid${userId}@email.com
              handler:
                body:
                - simple:
                   toVar: response
          - nextSequence: updateProfile
        - updateProfile:
          - updateProfileData:
              fromVar: response
              toVar: updatedProfile
          - thinkTime:
              duration: 5s
          - httpRequest:
              headers:
                Content-Type: "application/json"
                Authorization:
                  pattern: Bearer ${jwtToken}
              POST:
                pattern: /customer/byid/uid${userId}@email.com
              body:
                fromVar: updatedProfile
```
Change it to this?

```
          - httpRequest:
              headers:
                Authorization:
                  pattern: Bearer ${jwtToken}
              GET:
                pattern: /customer/byid/uid${userId}@email.com
              handler:
                body:
                - simple:
                   toVar: response
                - json:
                    query: .address.postalCode
                    replace:
                    - actions:
                        var: temp
                        actions:
                        - stringToInt: temp -> postalCode
                        - addToInt: postalCode++
                        pattern: ${postalCode}
                    processor:
                    - simple:
                        toVar: updated
                        format: BYTES
          - json:
              fromVar: response
              query: .address.postalCode
              replace: ${updated}
              processor:
                simple:
                  toVar: updatedProfile
                  format: BYTEBUF
          - nextSequence: updateProfile
        - updateProfile:
          - thinkTime:
              duration: 5s
          - httpRequest:
              headers:
                Content-Type: "application/json"
                Authorization:
                  pattern: Bearer ${jwtToken}
              POST:
                pattern: /customer/byid/uid${userId}@email.com
              body:
                fromVar: updatedProfile
```

**Comment by rvansa** [comment]
No, the `json` step shouldn't be there at all; the replacing handler will transform the reponse in place:
```yaml
         - httpRequest:
              headers:
                Authorization:
                  pattern: Bearer ${jwtToken}
              GET:
                pattern: /customer/byid/uid${userId}@email.com
              handler:
                body:
                - json:
                    query: .address.postalCode
                    replace:
                    - actions:
                        var: temp
                        actions:
                        - stringToInt: temp -> postalCode
                        - addToInt: postalCode++
                        pattern: ${postalCode}
                    processor:
                    - simple:
                        toVar: updated
                        format: BYTES
          - nextSequence: updateProfile
        - updateProfile:
          - thinkTime:
              duration: 5s
          - httpRequest:
              headers:
                Content-Type: "application/json"
                Authorization:
                  pattern: Bearer ${jwtToken}
              POST:
                pattern: /customer/byid/uid${userId}@email.com
              body:
                fromVar: updated
```

**Comment by mossuchida** [comment]
Original implementation has street number update also.  Is it possible to do it without using custom steps?
streetAddress1: "123 Main St." to streetAddress1: "124 Main St."

**Comment by rvansa** [comment]
Well, the missing piece would be some action to split a string into vars. However I guess it might be more appropriate to create a custom `i.h.api.processor.Transformer` that will do that. In a hindsight the `actions` transformer might be overly verbose (6 lines) - that's the price for being generic.
So, if you create your own transformers, you'd chain the `json` handlers:

```yaml
handler:
                body:
                - json:
                    query: .address.postalCode
                    replace:
                      myPostalCodeTransformer: {}
                    processor:
                      json:
                        query: .address.streetAddress1
                        replace:
                          myStreetAddressTransformer: {}
                        processor:
                        - simple:
                             toVar: updated
                             format: BYTES
```
I might think about more convenient ways to replace multiple fields at once.
